name: Liquibase Approval

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  generate-and-approve:
    runs-on: ubuntu-latest
    permissions:
      issues: write       # required by manual-approval
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Run Liquibase update-sql
        id: liquibase
        run: |
          # Run Liquibase to generate the SQL
          echo "hello" > update.sql

          BODY=$(cat update.sql | sed 's/%/%25/g; s/\n/%0A/g;')
          echo "body=$BODY" >> $GITHUB_OUTPUT

      - name: Manual approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: mac-hollister
          issue-title: "Liquibase SQL Approval"
          minimum-approvals: 1
          issue-body: |
            **Liquibase update-sql output:**

            ```
            ${{ steps.liquibase.outputs.body }}
            ```
